schedules/urls.py
from django.conf.urls import url

from . import views

app_name = 'schedules'
urlpatterns = [

    url(r'^$', views.build_view, name='home'),
    url(r'^schedules/$', views.build_view, name='schedule'),
    url(r'^schedules/settings/select$', views.SettingParameterUpdate.as_view(), name='settings-select'),
    url(r'^schedules/settings/rank/$', views.rank_settings, name='settings-rank'),
    url(r'^schedules/settings/rank/up/(?P<pk>[\d]+)$', views.rank_up, name='rank-up'),
    url(r'^schedules/settings/rank/down/(?P<pk>[\d]+)$', views.rank_down, name='rank-down'),
    url(r'^schedules/settings/auto$', views.SettingPreferenceUpdate.as_view(), name='settings-auto'),
    url(r'^schedules/select/$', views.ScheduleList.as_view(), name='select'),
    url(r'^schedules/select/(?P<pk>[\d]+)$', views.schedule_selected, name='schedule-selected'),
    url(r'^schedules/create$', views.ScheduleCreate.as_view(), name='schedule-create'),
    url(r'^schedules/duplicate/(?P<pk>[\d]+)/$', views.schedule_duplicate, name='duplicate'),
    url(r'^schedules/duplicate/(?P<pk>[\d]+)/confirm$', views.schedule_duplicate_confirmation, name='duplicate-confirmation'),
    url(r'^schedules/update$', views.update_files, name='update'),
    url(r'^schedules/building$', views.build_schedules, name='building'),
    url(r'^schedules/track$', views.track_state, name='track'),
    url(r'^schedules/redirect$', views.redirect, name='redirect'),
    url(r'^schedules/recommendation$', views.recommendations_view, name='recommendation'),
    url(r'^schedules/recommendation/add/(?P<pk>[\d]+)$', views.add_recommendation, name='recommendation_add'),
    url(r'^schedules/(?P<pk>[\d]+)/$', views.ScheduleDetail.as_view(), name='schedule-detail'),
    url(r'^schedules/(?P<pk>[\d]+)/delete$', views.ScheduleDelete.as_view(), name='schedule-delete'),
    url(r'^schedules/(?P<pk>[\d]+)/edit$', views.ScheduleUpdate.as_view(), name='schedule-update'),
    url(r'^schedules/get_ratios$', views.get_ratio, name='get-ratio'),
    url(r'^schedules/ratios/$', views.ratio_week_view, name='ratio-week'),
    url(r'^schedules/ratios/(?P<d>[\d]+)/(?P<s>[\d]+)/(?P<e>[\d]+)/$', views.ratio_window_view, name='ratio-window'),
    url(r'^schedules/special/$', views.rank_staphers_view, name='special'),
    url(r'^schedules/special/(?P<pk>[\d]+)/up$', views.rank_staphers_up, name='special-rank-up'),
    url(r'^schedules/special/(?P<pk>[\d]+)/down$', views.rank_staphers_down, name='special-rank-down'),
    url(r'^schedules/special/placement$', views.place_special_shifts, name='special-placement'),
    url(r'^schedules/special/results$', views.special_shifts_results, name='special-results'),

    url(r'^download/$', views.DownloadView.as_view(), name='download'),
    url(r'^download/individual$', views.download_individual, name='download-individual'),
    url(r'^download/masters$', views.download_masters, name='download-masters'),
    url(r'^download/meals$', views.download_meals, name='download-meals'),
    url(r'^download/analytics$', views.download_analytics, name='download-analytics'),

    url(r'^flag/create$', views.FlagCreate.as_view(), name='flag-create'),
    url(r'^flag/(?P<pk>[\d]+)/delete$', views.FlagDelete.as_view(), name='flag-delete'),

    url(r'^extras/$', views.Settings.as_view(), name='settings'),
    url(r'^extras/flags$', views.FlagSettings.as_view(), name='flag-settings'),
    url(r'^extras/qualifications$', views.QualificationSettings.as_view(), name='qualification-settings'),
    url(r'^extras/sets$', views.ShiftSetList.as_view(), name='shift-set-list'),

    url(r'^shifts/$', views.ShiftList.as_view(), name='shift-list'),
    url(r'^shifts/create$', views.ShiftCreate.as_view(), name='shift-create'),
    url(r'^shifts/(?P<pk>[\d]+)$', views.ShiftDetail.as_view(), name='shift-detail'),
    url(r'^shifts/(?P<pk>[\d]+)/schedule$', views.shift_schedule, name='shift-schedule'),
    url(r'^shifts/(?P<sh>[\d]+)/schedule/(?P<st>[\d]+)$', views.shift_schedule_stapher, name='shift-schedule-stapher'),
    url(r'^shifts/(?P<pk>[\d]+)/edit$', views.ShiftUpdate.as_view(), name='shift-update'),
    url(r'^shifts/(?P<pk>[\d]+)/delete$', views.ShiftDelete.as_view(), name='shift-delete'),
    url(r'^shifts/(?P<sort>[\D]*)/(?P<key>[\d]*)$', views.ShiftList.as_view(), name='shift-list-sort'),

    url(r'^staphers/$', views.StapherList.as_view(), name='stapher-list'),
    url(r'^staphers/create$', views.StapherCreate.as_view(), name='stapher-create'),
    url(r'^staphers/(?P<pk>[\d]+)/$', views.StapherDetail.as_view(), name='stapher-detail'),
    url(r'^staphers/(?P<pk>[\d]+)/edit$', views.StapherUpdate.as_view(), name='stapher-update'),
    url(r'^staphers/(?P<pk>[\d]+)/delete$', views.StapherDelete.as_view(), name='stapher-delete'),
    url(r'^staphers/(?P<pk>[\d]+)/schedule/$', views.stapher_schedule_view, name='stapher-schedule'),
    url(r'^staphers/(?P<pk>[\d]+)/schedule/add$', views.stapher_schedule_add, name='stapher-schedule-shifts'),
    url(r'^staphers/(?P<pk>[\d]+)/schedule/add/(?P<s>[\d]+)$', views.stapher_shift_scheduled, name='stapher-shift-scheduled'),
    url(r'^staphers/(?P<pk>[\d]+)/cover/$', views.stapher_cover, name='stapher-cover'),
    url(r'^staphers/preferences/(?P<pk>[\d]+)/$', views.stapher_preferences, name='stapher-preferences'),
    url(r'^staphers/preferences/(?P<pk>[\d]+)/up$', views.stapher_preferences_up, name='stapher-preferences-up'),
    url(r'^staphers/preferences/(?P<pk>[\d]+)/down$', views.stapher_preferences_down, name='stapher-preferences-down'),
    url(r'^staphers/preferences/(?P<pk>[\d]+)/(?P<f>[\d]+)$', views.stapher_preferences_add, name='stapher-preferences-add'),
    url(r'^staphers/preferences/delete/(?P<pk>[\d]+)$', views.stapher_preferences_delete, name='stapher-preferences-delete'),

    url(r'^qualification/create$', views.QualificationCreate.as_view(), name='qualification-create'),
    url(r'^qualification/(?P<pk>[\d]+)/delete$', views.QualificationDelete.as_view(), name='qualification-delete'),

    url(r'^staphing/(?P<pk>[\d]+)/delete$', views.StaphingDelete.as_view(), name='staphing-delete'),

    url(r'^set/create/$', views.ShiftSetCreate.as_view(), name='set-create'),
    url(r'^set/add/(?P<pk>[\d]+)$', views.shift_set_add, name='set-select-set'),
    url(r'^set/add/(?P<pk>[\d]+)/(?P<add>[\d]+)$', views.shift_set_add_from_set, name='set-add'),
    url(r'^set/delete/(?P<pk>[\d]+)$', views.ShiftSetDelete.as_view(), name='set-delete'),

    # Temp
    url(r'^sign_up/$', views.SignUpCreate.as_view(), name='sign_up'),
    url(r'^sign_up_success/$', views.SignUpSucess.as_view(), name='sign_up_success'),

]

staphd/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from schedules import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')), # Django auth urls for login/out & pw management
    url(r'^', include('schedules.urls'))
]

templates/sections/add_shifts.html
<form action="" method='POST' id='form' >{% csrf_token %}
	<button class='create_btn' id="form_save" type='submit'>Add Selected Shifts</button>
	<a class="button" type=button href="{% url 'schedules:shift-create' %}" target="_blank">New Shift</a>
	{% if form.errors %}
	<div class="error">
		<p>The shifts could not be added due to the following error:</p>
		<p>{{ form.errors.as_text }}</p>
	</div>
	{% endif %}
	<div id="form_div">
		<label for="added_shifts">Added shifts:</label>
		<table id="add_shifts_table">
			{% for row in new_shift_rows %}
			<tr id="add_shift_row">
				{% if forloop.first %}
				{% for cell in row %}
				<th>{{cell}}</th>
				{% endfor %}
				{% else %}
				{% for cell in row %}
				{% if cell %}

				<td class="add_shift_row_td" id="new_shift_{{cell.shift.id}}">
					<label for="id_added_shifts_{{forloop.counter0}}"></label>
					<input type="checkbox" name="added_shifts" value="{{cell.shift.id}}" class="new_shift_checkbox" id="id_added_shifts_{{forloop.counter0}}" onclick="toggle_highlighted({{cell.shift.id}})">
					<a id="new_shift_link" href='{{ cell.shift.get_absolute_url }}' target="_blank">
						{{cell.shift.title}}<br>{{cell.time_string}}
					</a>
				</td>

				{% else %}
				<td id="empty_cell"></td>
				{% endif %}
				{% endfor %}
				{% endif %}
			</tr>
			{% endfor %}
		</table>
	</div>
</form>
{% include "sections/highlight.html" %}

templates/sections/base.html
{% load staticfiles %}
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <title>staphd.com</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block head_content %}{% endblock %}
</head>
<body>
	{% block content %}{% endblock %}
</body>
</html>

templates/sections/highlight.html
<script type="text/javascript">
	function toggle_highlighted(shift_id) {
		var shift_id_string = 'new_shift_' + shift_id;
		var shift = document.getElementById(shift_id_string);
		if (shift.style.backgroundColor === "lime") {
			shift.style.backgroundColor = "silver";
			shift.style.fontWeight = "normal";
		} else {
			shift.style.backgroundColor = "lime";
			shift.style.fontWeight = "bold";
		}
	}
</script>

templates/sections/nav.html
{% extends "sections/base.html" %}
{% load static from staticfiles %}
{% block head_content%}
	<link rel="stylesheet" href="{% static 'css/delete.css' %}">
	<link rel="stylesheet" href="{% static 'css/detail.css' %}">
	<link rel="stylesheet" href="{% static 'css/download.css' %}">
	<link rel="stylesheet" href="{% static 'css/form.css' %}">
	<link rel="stylesheet" href="{% static 'css/list.css' %}">
	<link rel="stylesheet" href="{% static 'css/nav.css' %}">
	<link rel="stylesheet" href="{% static 'css/page.css' %}">
	<link rel="stylesheet" href="{% static 'css/schedule.css' %}">
	<link rel="stylesheet" href="{% static 'css/schedule_settings.css' %}">
	<link rel="stylesheet" href="{% static 'css/stapher_schedule.css' %}">
	<link rel="stylesheet" href="{% static 'css/recommendation.css' %}">
	<link rel="stylesheet" href="{% static 'css/shift_set.css' %}">
	<link rel="stylesheet" href="{% static 'css/ratio.css' %}">
	<link rel="stylesheet" href="{% static 'css/cover.css' %}">
	<link rel="stylesheet" href="{% static 'css/special_shift.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
{% endblock %}
{% block content %}
<div id="navbar">
	<div id="title">staphd.com</div>
	<div id="user">
		user: {{ user.get_username }}, <a href="{% url 'logout'%}">Log out</a>
	</div>
	<ul id="links">
		{% if at_build %}
		<li class="current_link"><a href="{% url 'schedules:schedule'%}">Build</a></li>
		{% else %}
		<li><a href="{% url 'schedules:schedule'%}">Build</a></li>
		{% endif %}
		{% if at_staph %}
		<li class="current_link"><a href="{% url 'schedules:stapher-list'%}">Staphers</a></li>
		{% else %}
		<li><a href="{% url 'schedules:stapher-list'%}">Staphers</a></li>
		{% endif %}
		{% if at_shifts %}
		<li class="current_link"><a href="{% url 'schedules:shift-list' %}">Shifts</a></li>
		{% else %}
		<li><a href="{% url 'schedules:shift-list' %}">Shifts</a></li>
		{% endif %}
		{% if at_settings %}
		<li class="current_link"><a href="{% url 'schedules:settings' %}">Extras</a></li>
		{% else %}
		<li><a href="{% url 'schedules:settings' %}">Extras</a></li>
		{% endif %}
	</ul>
</div>
{% block page %}
<!-- page content -->
{% endblock %}

{% endblock %}

templates/sections/save_first.html
<script type="text/javascript">
	$(document).ready(function(){
		var form = $('#form'), original = form.serialize()
		
		form.submit(function(){
			window.onbeforeunload = null
		})

		window.onbeforeunload = function(){
			if (form.serialize() != original)
				return 'Are you sure you want to leave?'
		}
	})
</script>

templates/sections/shifts_from_flag.html
<script type="text/javascript">
	function toggle_set_flag(flag_id, shift_set_id, check) {
		var all_shifts = {{shifts_arr}};
		var shifts_to_check = [];
		for (i = 0; i < all_shifts.length; i++) {
			var arr = all_shifts[i];
			var shift = arr[0];
			var set = arr[1];
			var flags = arr[2];
			if (set === shift_set_id){
				for (j = 0; j < flags.length; j++) {
					var flag = flags[j];
					if (flag === flag_id) {
						shifts_to_check.push(shift);
					}
				}
			}
		}
		for (i = 0; i < shifts_to_check.length; i++) {
			var id = shifts_to_check[i];
			var shift_id_str = "id_added_shifts_" + id;
			var shift_elem = document.getElementById(shift_id_str);
			shift_elem.checked = check;
			var li_elem_id = "added_shift_li_" + id;
			var li_elem = document.getElementById(li_elem_id);
			if (check) {
				li_elem.style.backgroundColor = "lime";
				li_elem.style.fontWeight = "bold";
			} else {
				li_elem.style.backgroundColor = "#EEEEEE";
				li_elem.style.fontWeight = "normal";
			}
		}
	}


	function toggle_set(shift_set_id, check) {
		var all_shifts = {{shifts_arr}};
		var shifts_to_check = [];
		for (i = 0; i < all_shifts.length; i++) {
			var arr = all_shifts[i];
			var shift = arr[0];
			var set = arr[1];
			var flags = arr[2];
			if (set === shift_set_id){
				shifts_to_check.push(shift);
			}
		}
		for (i = 0; i < shifts_to_check.length; i++) {
			var id = shifts_to_check[i];
			var shift_id_str = "id_added_shifts_" + id;
			var shift_elem = document.getElementById(shift_id_str);
			shift_elem.checked = check;
			var li_elem_id = "added_shift_li_" + id;
			var li_elem = document.getElementById(li_elem_id);
			if (check) {
				li_elem.style.backgroundColor = "lime";
				li_elem.style.fontWeight = "bold";
			} else {
				li_elem.style.backgroundColor = "#EEEEEE";
				li_elem.style.fontWeight = "normal";
			}
		}
	}

	function toggle_set_shifts(shift_set_id) {
		var set_id_string = 'set_' + shift_set_id;
		var set_elem = document.getElementById(set_id_string);
		if (set_elem.checked) {
			toggle_set(shift_set_id, true);
		} else {
			toggle_set(shift_set_id, false);
		}
	}

	function toggle_shifts(flag_id, shift_set_id) {
		var flag_id_string = 'f_' + flag_id + '_s_' + shift_set_id;
		var flag_elem = document.getElementById(flag_id_string);
		if (flag_elem.checked) {
			toggle_set_flag(flag_id, shift_set_id, true);
		} else {
			toggle_set_flag(flag_id, shift_set_id, false);
		}
	}

	function toggle_highlighted(shift_id) {
		var shift_id_string = 'added_shift_li_' + shift_id;
		var shift_elem = document.getElementById(shift_id_string);
		var checkbox_id_string = 'id_added_shifts_' + shift_id;
		var checkbox_elem = document.getElementById(checkbox_id_string);
		if (checkbox_elem.checked) {
			shift_elem.style.backgroundColor = "lime";
			shift_elem.style.fontWeight = "bold";
		} else {
			shift_elem.style.backgroundColor = "#EEEEEE";
			shift_elem.style.fontWeight = "normal";
			
		}
	}
</script>

templates/sections/show_schedules.html
<script type="text/javascript">
	function toggle_schedule(stapher_id) {
		var id_string = 'stapher_schedule_' + stapher_id
		var schedule = document.getElementById(id_string);
		if (schedule.style.display === "table") {
			schedule.style.display = "none";
		} else {
			schedule.style.display = "table";
		}
	}
</script>

templates/sections/splash.html
{% extends "sections/base.html" %}
{% load static from staticfiles %}
{% block head_content%}
	<link rel="stylesheet" href="{% static 'css/splash.css' %}">
{% endblock %}
{% block content %}
<div class="splash-bg">
	<video loop muted autoplay poster="{% static 'images/lake.jpg' %}" src="{% static 'videos/lake.mov' %}" class="splash-bg__video"></video>
</div>
<div class="splash-header">
	<h1>staphd.com</h1>
</div>
{% block login %}
{% endblock %}
{% endblock %}

templates/sections/week_view.html
{% for row in all_rows_for_time %}
<tr>
	{% if forloop.first %}
	{% for day in row %}
	<th>{{day}}</th>
	{% endfor %}
	{% else %}
	{% for cell in row %}
	{% if cell%}
	{% if cell.new_shift %}
	<td class="scheduled_time" id="new_shift" rowspan="{{cell.span}}">
	{% else %}
	<td class="scheduled_time" rowspan="{{cell.span}}">
	{% endif %}
		{% if can_delete %}
		<a href="{% url 'schedules:staphing-delete' pk=cell.staphing_id %}"><i class="fa fa-times-rectangle" id="delete_icon"></i></a>
		{% endif %}
		<a id="new_shift_link" href='{{ cell.shift.get_absolute_url }}' target="_blank">
			{{cell.title}}
		</a>
	</td>
	{% else %}
	<td id="non_scheduled_time"></td>
	{% endif %}
	{% endfor %}
	{% endif %}
</tr>
{% endfor %}