schedules/urls.py
from django.conf.urls import url

from . import views

app_name = 'schedules'
urlpatterns = [

    url(r'^$', views.build_view, name='home'),
    url(r'^schedules/$', views.build_view, name='schedule'),
    url(r'^schedules/settings/select$', views.SettingParameterUpdate.as_view(), name='settings-select'),
    url(r'^schedules/settings/rank/$', views.rank_settings, name='settings-rank'),
    url(r'^schedules/settings/rank/up/(?P<pk>[\d]+)$', views.rank_up, name='rank-up'),
    url(r'^schedules/settings/rank/down/(?P<pk>[\d]+)$', views.rank_down, name='rank-down'),
    url(r'^schedules/settings/auto$', views.SettingPreferenceUpdate.as_view(), name='settings-auto'),
    url(r'^schedules/select/$', views.ScheduleList.as_view(), name='select'),
    url(r'^schedules/select/(?P<pk>[\d]+)$', views.schedule_selected, name='schedule-selected'),
    url(r'^schedules/create$', views.ScheduleCreate.as_view(), name='schedule-create'),
    url(r'^schedules/duplicate/(?P<pk>[\d]+)/$', views.schedule_duplicate, name='duplicate'),
    url(r'^schedules/duplicate/(?P<pk>[\d]+)/confirm$', views.schedule_duplicate_confirmation, name='duplicate-confirmation'),
    url(r'^schedules/update$', views.update_files, name='update'),
    url(r'^schedules/building$', views.build_schedules, name='building'),
    url(r'^schedules/track$', views.track_state, name='track'),
    url(r'^schedules/redirect$', views.redirect, name='redirect'),
    url(r'^schedules/recommendation$', views.recommendations_view, name='recommendation'),
    url(r'^schedules/recommendation/add/(?P<pk>[\d]+)$', views.add_recommendation, name='recommendation_add'),
    url(r'^schedules/(?P<pk>[\d]+)/$', views.ScheduleDetail.as_view(), name='schedule-detail'),
    url(r'^schedules/(?P<pk>[\d]+)/delete$', views.ScheduleDelete.as_view(), name='schedule-delete'),
    url(r'^schedules/(?P<pk>[\d]+)/edit$', views.ScheduleUpdate.as_view(), name='schedule-update'),
    url(r'^schedules/get_ratios$', views.get_ratio, name='get-ratio'),
    url(r'^schedules/ratios/$', views.ratio_week_view, name='ratio-week'),
    url(r'^schedules/ratios/(?P<d>[\d]+)/(?P<s>[\d]+)/(?P<e>[\d]+)/$', views.ratio_window_view, name='ratio-window'),
    url(r'^schedules/special/$', views.rank_staphers_view, name='special'),
    url(r'^schedules/special/(?P<pk>[\d]+)/up$', views.rank_staphers_up, name='special-rank-up'),
    url(r'^schedules/special/(?P<pk>[\d]+)/down$', views.rank_staphers_down, name='special-rank-down'),
    url(r'^schedules/special/placement$', views.place_special_shifts, name='special-placement'),
    url(r'^schedules/special/results$', views.special_shifts_results, name='special-results'),

    url(r'^download/$', views.DownloadView.as_view(), name='download'),
    url(r'^download/individual$', views.download_individual, name='download-individual'),
    url(r'^download/masters$', views.download_masters, name='download-masters'),
    url(r'^download/meals$', views.download_meals, name='download-meals'),
    url(r'^download/analytics$', views.download_analytics, name='download-analytics'),

    url(r'^flag/create$', views.FlagCreate.as_view(), name='flag-create'),
    url(r'^flag/(?P<pk>[\d]+)/delete$', views.FlagDelete.as_view(), name='flag-delete'),

    url(r'^extras/$', views.Settings.as_view(), name='settings'),
    url(r'^extras/flags$', views.FlagSettings.as_view(), name='flag-settings'),
    url(r'^extras/qualifications$', views.QualificationSettings.as_view(), name='qualification-settings'),
    url(r'^extras/sets$', views.ShiftSetList.as_view(), name='shift-set-list'),

    url(r'^shifts/$', views.ShiftList.as_view(), name='shift-list'),
    url(r'^shifts/create$', views.ShiftCreate.as_view(), name='shift-create'),
    url(r'^shifts/(?P<pk>[\d]+)$', views.ShiftDetail.as_view(), name='shift-detail'),
    url(r'^shifts/(?P<pk>[\d]+)/schedule$', views.shift_schedule, name='shift-schedule'),
    url(r'^shifts/(?P<sh>[\d]+)/schedule/(?P<st>[\d]+)$', views.shift_schedule_stapher, name='shift-schedule-stapher'),
    url(r'^shifts/(?P<pk>[\d]+)/edit$', views.ShiftUpdate.as_view(), name='shift-update'),
    url(r'^shifts/(?P<pk>[\d]+)/delete$', views.ShiftDelete.as_view(), name='shift-delete'),
    url(r'^shifts/(?P<sort>[\D]*)/(?P<key>[\d]*)$', views.ShiftList.as_view(), name='shift-list-sort'),

    url(r'^staphers/$', views.StapherList.as_view(), name='stapher-list'),
    url(r'^staphers/create$', views.StapherCreate.as_view(), name='stapher-create'),
    url(r'^staphers/(?P<pk>[\d]+)/$', views.StapherDetail.as_view(), name='stapher-detail'),
    url(r'^staphers/(?P<pk>[\d]+)/edit$', views.StapherUpdate.as_view(), name='stapher-update'),
    url(r'^staphers/(?P<pk>[\d]+)/delete$', views.StapherDelete.as_view(), name='stapher-delete'),
    url(r'^staphers/(?P<pk>[\d]+)/schedule/$', views.stapher_schedule_view, name='stapher-schedule'),
    url(r'^staphers/(?P<pk>[\d]+)/schedule/add$', views.stapher_schedule_add, name='stapher-schedule-shifts'),
    url(r'^staphers/(?P<pk>[\d]+)/schedule/add/(?P<s>[\d]+)$', views.stapher_shift_scheduled, name='stapher-shift-scheduled'),
    url(r'^staphers/(?P<pk>[\d]+)/cover/$', views.stapher_cover, name='stapher-cover'),
    url(r'^staphers/preferences/(?P<pk>[\d]+)/$', views.stapher_preferences, name='stapher-preferences'),
    url(r'^staphers/preferences/(?P<pk>[\d]+)/up$', views.stapher_preferences_up, name='stapher-preferences-up'),
    url(r'^staphers/preferences/(?P<pk>[\d]+)/down$', views.stapher_preferences_down, name='stapher-preferences-down'),
    url(r'^staphers/preferences/(?P<pk>[\d]+)/(?P<f>[\d]+)$', views.stapher_preferences_add, name='stapher-preferences-add'),
    url(r'^staphers/preferences/delete/(?P<pk>[\d]+)$', views.stapher_preferences_delete, name='stapher-preferences-delete'),

    url(r'^qualification/create$', views.QualificationCreate.as_view(), name='qualification-create'),
    url(r'^qualification/(?P<pk>[\d]+)/delete$', views.QualificationDelete.as_view(), name='qualification-delete'),

    url(r'^staphing/(?P<pk>[\d]+)/delete$', views.StaphingDelete.as_view(), name='staphing-delete'),

    url(r'^set/create/$', views.ShiftSetCreate.as_view(), name='set-create'),
    url(r'^set/add/(?P<pk>[\d]+)$', views.shift_set_add, name='set-select-set'),
    url(r'^set/add/(?P<pk>[\d]+)/(?P<add>[\d]+)$', views.shift_set_add_from_set, name='set-add'),
    url(r'^set/delete/(?P<pk>[\d]+)$', views.ShiftSetDelete.as_view(), name='set-delete'),

    # Temp
    url(r'^sign_up/$', views.SignUpCreate.as_view(), name='sign_up'),
    url(r'^sign_up_success/$', views.SignUpSucess.as_view(), name='sign_up_success'),

]

staphd/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from schedules import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')), # Django auth urls for login/out & pw management
    url(r'^', include('schedules.urls'))
]

schedules/views.py
import boto3
import botocore
import datetime
import json
import os

from celery import current_task
from celery.result import AsyncResult
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.db.models import Q
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404, render, redirect
from django.template import RequestContext
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from operator import attrgetter
from staphd.celery import app

from .analytics import get_readable_time
from .forms import WeekdayForm, AddShiftsForm, FlagCreateForm, SignUpCreateForm, ScheduleCreateForm, SettingsParameterForm, SettingsPreferenceForm, ShiftCreateForm, StapherCreateForm, QualificationCreateForm, ShiftSetCreateForm, AddShiftsToSetForm
from .models import Flag, Schedule, Shift, ShiftSet, Stapher, Staphing, Master, Parameter, Qualification, ShiftPreference
from .models import Settings as ScheduleBuildingSettings
from .special_shifts import get_special_shift_flags, swap_shift_preferences
from .tasks import build_schedules_task, update_files_task, find_ratios_task, place_special_shifts_task, add_shifts_to_set_task
from .helpers import get_shifts_to_add, get_week_schedule_view_info, get_ratio_table, get_ratio_tables_in_window, get_stapher_breakdown_table, get_time_from_string
from .tasks import RECOMMENDATION_REDIRECT, RATIO_REDIRECT, SPECIAL_SHIFT_REDIRECT




# Download Based Views
class DownloadView(LoginRequiredMixin, TemplateView):
	template_name = 'schedules/download.html'

	def get_context_data(self, *args, **kwargs):
		context = super(DownloadView, self).get_context_data(*args, **kwargs)
		try:
			active_schedule = Schedule.objects.get(active = True)
		except:
			active_schedule = None
		last_updated = Schedule.objects.latest('excel_updated')
		up_to_date = False
		from_current_schedule = False
		if active_schedule:
			from_current_schedule = (active_schedule == last_updated)
			up_to_date = (last_updated.updated_on < last_updated.excel_updated)
		latest_excel_deleted = cache.get('latest_excel_deleted')
		clean_excels = from_current_schedule and up_to_date and not latest_excel_deleted
		if clean_excels:
			clean_msg = f'Excel files are up to date.'
		elif latest_excel_deleted:
			last_updated = 'a deleted schedule.'
			clean_msg = f'Excel files match a deleted schedule, please update Excel files'
		elif from_current_schedule:
			clean_msg = f'These files are not up to date. Please update Excel files for {active_schedule}'
		elif up_to_date:
			clean_msg = f'Excel files match {last_updated} - not the current schedule ({active_schedule})'
		else:
			clean_msg = f'Files do not match {last_updated}. Please update the Excel files for {last_updated} or {active_schedule} before downloading'

		context['last_updated'] = last_updated
		context['clean_excels'] = clean_excels
		context['clean_msg'] = clean_msg
		return context

@login_required
def download_file(request, filename):
	path = 'static/xlsx/' + filename
	s3 = boto3.resource('s3')
	try:
		s3.Bucket('staphd').download_file(filename, path)
		with open(path, 'rb') as file:
			response = HttpResponse(file.read(), content_type="application/xlsx")
			response['Content-Disposition'] = 'inline; filename=' + filename
			return response
	except botocore.exceptions.ClientError as e:
		if e.response['Error']['Code'] == "404":
			print("The object does not exist.")
		raise Http404

@login_required
def download_individual(request, *args, **kwargs):
	return download_file(request, 'schedules.xlsx')

@login_required
def download_masters(request, *args, **kwargs):
	return download_file(request, 'masters.xlsx')

@login_required
def download_meals(request, *args, **kwargs):
	return download_file(request, 'meal-masters.xlsx')

@login_required
def download_analytics(request, *args, **kwargs):
	return download_file(request, 'analytics.xlsx')


# Schedule Building based Views
@login_required
def build_view(request, *args, **kwargs):
	template = 'schedules/schedule.html'
	try:
		schedule = Schedule.objects.get(active__exact = True)
		context = {'schedule':schedule.title}
		context['percent_complete'] = schedule.get_percent_complete()
	except:
		context = {}
	task_id = cache.get('current_task_id')
	if task_id:
		template = 'schedules/progress.html'
		context['task_id'] = task_id
	context['at_build'] = True
	cache.delete('no_redirect')
	return render(request, template, context) 

class SettingParameterUpdate(LoginRequiredMixin, UpdateView):
	template_name = 'schedules/settings_select.html'
	form_class = SettingsParameterForm
	success_url = reverse_lazy('schedules:settings-rank')

	def get_queryset(self):
		return ScheduleBuildingSettings.objects.all()

	def get_object(self):
		try:
			return ScheduleBuildingSettings.objects.get()
		except:
			return Http404

	def get_context_data(self, *args, **kwargs):
		context = super(SettingParameterUpdate, self).get_context_data(*args, **kwargs)
		context['select'] = True
		context['all_parameters'] = Parameter.objects.all().order_by('rank')
		context['at_build'] = True
		return context

@login_required
def rank_settings(request, *args, **kwargs):
	try:
		settings = ScheduleBuildingSettings.objects.get()
		parameters = settings.parameters.all()
		template = 'schedules/settings_rank.html'
		context = {}
		context['rank'] = True
		context['parameters'] = settings.parameters.all().order_by('rank')
		context['at_build'] = True
		return render(request, template, context)
	except:
		return Http404

@login_required
def swap_rank(request, param_id, parameters):
	search_param = None
	swap_param = None
	for param in parameters:
		if param.id == param_id:
			search_param = param
			break
		swap_param = param
	if search_param and swap_param:
		search_param.swap_rankings(swap_param)
	return rank_settings(request)

@login_required
def rank_up(request, *args, **kwargs):
	try:
		up_param_id = int(kwargs['pk'])
		settings = ScheduleBuildingSettings.objects.get()
		parameters = settings.parameters.all().order_by('rank') #Highest Raking to Lowest
		return swap_rank(request, up_param_id, parameters)
	except:
		return Http404

@login_required
def rank_down(request, *args, **kwargs):
	try:
		down_param_id = int(kwargs['pk'])
		settings = ScheduleBuildingSettings.objects.get()
		parameters = settings.parameters.all().order_by('-rank') #Lowest Raking to Highest
		return swap_rank(request, down_param_id, parameters)
	except:
		return Http404

class SettingPreferenceUpdate(LoginRequiredMixin, UpdateView):
	template_name = 'schedules/settings_auto.html'
	form_class = SettingsPreferenceForm
	success_url = reverse_lazy('schedules:schedule')

	def get_queryset(self):
		return ScheduleBuildingSettings.objects.all()

	def get_object(self):
		try:
			return ScheduleBuildingSettings.objects.get()
		except:
			return Http404

	def get_context_data(self, *args, **kwargs):
		context = super(SettingPreferenceUpdate, self).get_context_data(*args, **kwargs)
		context['auto'] = True
		settings = self.get_object()
		context['auto_schedule'] = settings.auto_schedule
		context['auto_threshold'] = settings.auto_threshold
		context['random'] = settings.break_ties_randomly()
		context['rank_based'] = settings.ranked_wins_break_ties()
		context['at_build'] = True
		return context

@login_required
@csrf_exempt
def build_schedules(request, *args, **kwargs):
	try:
		schedule = Schedule.objects.get(active__exact = True)
	except:
		return render(request,'schedules/schedule.html', {'schedule_error_message':'Must select a schedule first.'})
	task_id = cache.get('current_task_id')
	if not task_id:
		schedule_id = schedule.id
		task = build_schedules_task.delay(schedule_id)
		task_id = task.task_id
		cache.set('current_task_id', task_id, 3000)
		cache.set('no_redirect', True, None)
	request.session['task_id'] = task_id
	context = {'task_id':task_id}
	context['schedule'] = schedule.title
	context['at_build'] = True
	return render(request,'schedules/progress.html', context)

@login_required
@csrf_exempt
def update_files(request, *args, **kwargs):
	context = {}
	task_id = cache.get('current_task_id')
	if not task_id:
		try:
			schedule = Schedule.objects.get(active__exact = True)
			schedule_id = schedule.id
		except:
			return render(request,'schedules/schedule.html', {'update_error_message':'Must select a schedule first.'})
		staphings = Staphing.objects.filter(schedule__id = schedule_id)
		if not staphings:
			template = 'schedules/schedule.html'
			context['update_error_message'] = 'No Shifts Scheduled - Must Schedule Shifts First'
		else:
			template = 'schedules/progress.html'
			task = update_files_task.delay(schedule_id)
			task_id = task.task_id
			cache.set('current_task_id', task_id, 3000)
			cache.set('no_redirect', True, None)
			cache.set('latest_excel_deleted', False, None)
	else:
		template = 'schedules/progress.html'
		context['update_error_message'] = 'Please wait for the current task to complete.'

	request.session['task_id'] = task_id
	context['task_id'] = task_id
	context['schedule'] = schedule.title
	context['at_build'] = True
	return render(request, template, context)

@login_required
@csrf_exempt
def track_state(request, *args, **kwargs):
	""" A view to report the progress of a task to the user """
	data = 'Fail'
	task_id = cache.get('current_task_id')
	if request.is_ajax():
		if 'task_id' in request.POST.keys() and request.POST['task_id']:
			task_id = request.POST['task_id']
			print(f'			task_id -> {task_id}')
			task = app.AsyncResult(task_id)
			data = task.result or task.state
			print(f'			data -> {data}')
			task_running = not task.ready() and not isinstance(data, str)

schedules/templates/schedules/delete.html
{% extends "sections/nav.html" %}
{% block page %}
<div id="page">
	<form id='delete_form' action="" method="post">{% csrf_token %}
		<h1>Are you sure you want to delete:<br>"{{ object }}"?</h1>
		{% for to_delete in deleted_extras %}
		{% if forloop.first %}
		<h2><u>Doing so will also delete:</u></h2>
		{% endif %}
		<h4>- {{to_delete}} </h4>
		{% endfor %}
		<div id='delete_form_btns'>
			{% if schedule_id %}
				<a class="link_btn" href="{% url 'schedules:schedule-detail' pk=schedule_id %}">Cancel</a>
			{% else %}
				<a class="link_btn" href='{{ object.get_absolute_url }}'>Cancel</a>
			{% endif %}
			<input class="final_delete_btn" type="submit" value="Delete" />
		</div>
	</form>
</div>
{% endblock %}

schedules/templates/schedules/schedule.html
{% extends "sections/nav.html" %}
{% block page %}
<div id="page">
	<div id="schedule_settings">
		<a class="button" href="{% url 'schedules:settings-select' %}">Schedule Building Settings</a>
	</div>
	<div id="update_excel_form">
		{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
		<form action="{% url 'schedules:update' %}" method="post">
			{% csrf_token %}
			<input class="button" type="submit" value="Update Excel Files">
		</form>
		{% if update_error_message %}<p><strong>{{ update_error_message }}</strong></p>{% endif %}
	</div>
	<div id="schedule_information">
		{% if schedule %}
		<h2><strong>{{ schedule }}</strong>{%if percent_complete %} - {{percent_complete}}% complete. {% endif %}</h2>
		<a class="button" href="{% url 'schedules:get-ratio' %}">Check Ratios</a>
		{% else %}
		<h2><strong>No Current Schedules</strong></h2>
		{% endif %}
		<a class="button" href="{% url 'schedules:select' %}">Select New Schedules</a>
	</div>
	<div id="build_schedule_form">
		{% if error_message %}<h5><strong>{{ error_message }}</strong></h5>{% endif %}
		<form action="{% url 'schedules:building' %}" method="post">
			{% csrf_token %}
			<input class="big_button" type="submit" value="Build Schedules">
		</form>
		{% if schedule_error_message %}<p><strong>{{ schedule_error_message }}</strong></p>{% endif %}
	</div>
	{% block progress %}{% endblock %}
</div>
{% endblock %}

schedules/templates/schedules/schedule_list.html
{% extends "sections/nav.html" %}
{% block page %}
<div id="page">
	<div class="select_header">
		{% if schedule %}
			<h1>Current Schedules are "{{schedule}}"</h1>
			<a class="button" type=button href="{% url 'schedules:schedule-detail' pk=schedule.id %}">View {{schedule}}</a>
		{% else %}
			<h1>No Schedules Selected</h1>
		{% endif %}
		<a class="create_btn" type=button href="{% url 'schedules:schedule-create' %}">New Schedules</a>
		<hr style="background-color: grey; height:1px; margin-top: 10px;">
	</div>
	<div class="select_list">
		{% if object_list %}
			<h1>Select New Schedules:</h1>
			{% for obj in object_list %}
				<ul class="schedule_links">
					<li><h2>{{obj}}</h2></li>
					<li><a class="list_btn" href="{% url 'schedules:schedule-detail' pk=obj.id %}">View</a></li>
					<li><a class="create_btn" href='{{ obj.get_absolute_url }}'>Select</a></li>
					{% if schedule and obj.shift_set.id == schedule.shift_set.id %}
					<li><a class="delete_button" href="{% url 'schedules:duplicate-confirmation' pk=obj.id %}">Erase Current Schedules & Duplicate "{{obj.title}}"</a></li>
					{% endif %}
				</ul>
			{% endfor %}
		{% else %}
			<h3> No Schedules found.</h3><br>
			<p>Select "New Schedules" to create a group of schedules.</p>
		{% endif %}			
	</div>
</div>
{% endblock %}

schedules/templates/schedules/settings.html
{% extends "sections/nav.html" %}
{% block page %}
<div id="page">
	<h1>Schedule Building Settings:</h1>
	<div id="setting_selector">
		{% if select %}
			<a class="button" id="setting_selected" href="{% url 'schedules:settings-select' %}">Select Parameters</a>
		{% else %}
			<a class="button" href="{% url 'schedules:settings-select' %}">Select Parameters</a>
		{% endif %}
		{% if rank %}
			<a class="button" id="setting_selected" href="{% url 'schedules:settings-rank' %}">Edit Parameter Rank</a>
		{% else %}
			<a class="button" href="{% url 'schedules:settings-rank' %}">Edit Parameter Rank</a>
		{% endif %}
		{% if auto %}
			<a class="button" id="setting_selected" href="{% url 'schedules:settings-auto' %}">Edit Automation Preferences</a>
		{% else %}
			<a class="button" href="{% url 'schedules:settings-auto' %}">Edit Automation Preferences</a>
		{% endif %}
	</div>
	<hr style="background-color: grey; height:1px; margin: 10px;">
	{% block settings_form %}{% endblock %}
</div>
{% endblock %}

schedules/templates/schedules/settings_rank.html
{% extends "schedules/settings.html" %}
{% block settings_form %}
<h1>Parameter Rankings:</h1>
<table id="parameters_table">
	<tr>
		<th></th>
		<th id="title_tablehead">Title</th>
		<th>Description
			<div class="tooltip">
				<span class="tooltiptext" id="tooltiptext_small">
					Given the shift to be scheduled, select the worker that ...
				</span>
				(?)
			</div>
		</th>
	</tr>
	{% for param in parameters %}
	<tr>
		<td id="parameters_table_rank"><strong>{{forloop.counter}}</strong></td>
		<td id="parameters_table_text"><strong>{{param.title}}</strong></td>
		<td id="parameters_table_text">{{param.description}}</td>
		<td>
			<ul id="up_down_vote">
				<li><a href="{% url 'schedules:rank-up' pk=param.id %}"><i class="fa fa-sort-up"></i></a></li>
				<li><a href="{% url 'schedules:rank-down' pk=param.id %}"><i class="fa fa-sort-down"></i></a></li>
			</ul>
		</td>
	</tr>
	{% endfor %}
</table>
<br>
<div class="tooltip">More Info
	<span class="tooltiptext">
		Parameter Rankings are used for two things:<br><br>
		1. Displaying Suggestions<br>
		- When suggesting who should get which shift, the parameters will be displayed left to right based on their rank.<br><br>
		2. Breaking Ties<br>
		- If you chose so, you can have ties be broken by deciding whichever worker is the best choice in the highest ranked parameter.<br>
		- More about breaking ties is explained on the next page! Woo hoo!<br><br>
		Feel free to rank in whatever way you would like!
	</span>
</div>
<a class="button" href="{% url 'schedules:settings-auto' %}">Next</a>
{% endblock %}

schedules/templates/schedules/shift_set_list.html
{% extends "sections/nav.html" %}
{% block page %}
<div id="page">
	<div id="form_header">
		<h1> Add Shifts to {{shift_set.title}} - </h1>
		<a class='button' id="form_cancel" href='{% url cancel_url %}'>Cancel</a>
	</div>
	<a class="delete_button" href="{% url 'schedules:set-delete' pk=shift_set.id %}">Delete {{shift_set}}</a>
	<hr style="background-color: grey; height:1px; margin-top: 10px;">
	<h1>Add Shifts From:</h1>
	<div id="shift_set_div" >
		<ul>
			{% for set in other_shift_sets %}
			<li><a class="button" href="{% url 'schedules:set-add' pk=shift_set.id add=set.id %}">{{set}}</a></li>
			<br>
			{% endfor %}
		</ul>

	</div>
</div>
{% endblock %}

schedules/templates/schedules/stapher_preferences.html
{% extends "sections/nav.html" %}
{% block page %}
<div id="page">
	<h1>Special Shift Preferences for {{stapher}}</h1>
	<a class="button" href="{% url 'schedules:special' %}">Back to Ranking</a>
	<br>
	<br>
	<div class="preferences_div">
		<h2>Add Prefences</h2>
		<ul>
			<table id="ranking_table">
				{% for flag in flags_to_add %}
				<tr>
					<td class="ranking_table_data" id="ranking_table_text">{{flag}}</td>
					<td class="ranking_table_data" id="ranking_table_text">
						<a id="add_link" href="{% url 'schedules:stapher-preferences-add' pk=stapher.id f=flag.id %}">Add</a>
					</td>
				</tr>
				{% endfor %}
			</table>
		</ul>
	</div>
	<div class="preferences_div" id="preferences_div_left">
		{% if staphers_preferences %}
		<h2>Stapher Prefences</h2>
		{% endif %}
		<table id="ranking_table">
			{% for pref in staphers_preferences %}
			<tr>
				<td class="ranking_table_data" id="ranking_table_rank"><strong>{{forloop.counter}}</strong></td>
				<td class="ranking_table_data" id="ranking_table_text">{{pref.flag}}</td>
				<td class="ranking_table_data" id="ranking_table_text">
					<a id="remove_link" href="{% url 'schedules:stapher-preferences-delete' pk=pref.id %}">Remove</a>
				</td>
				<td class="ranking_table_data">
					<ul id="up_down_vote">
						<li>
							<a id="rating_link" href="{% url 'schedules:stapher-preferences-up' pk=pref.id %}"><i class="fa fa-sort-up"></i></a>
						</li>
						<li>
							<a id="rating_link" href="{% url 'schedules:stapher-preferences-down' pk=pref.id %}"><i class="fa fa-sort-down"></i></a>
						</li>
					</ul>
				</td>
			</tr>
			{% endfor %}
		</table>
	</div>
</div>
{% endblock %}